### ISSUE TITLE
Update esbuild-visualizer peer dependency

### ISSUE THREAD

**Issue by coyoteecd** [adriencaccia/serverless-analyze-bundle-plugin#14]
A peer dependency of this package, `esbuild-visualizer@0.4.0`, has been released recently.
Could you modify peerDependencies in package.json to include this version and publish a patch version of this plugin with that change?

**Comment by adriencaccia** [comment]
Hey @coyoteecd, thanks for the issue.

I just checked the changelog https://github.com/btd/esbuild-visualizer/blob/master/CHANGELOG.md#040, and it seems that the visualizer is now available through code and not only the CLI. This means that we can directly call the `visualizer` function in https://github.com/adriencaccia/serverless-analyze-bundle-plugin/blob/0e65d0c8cb4b51b716de0cdde133a7c53a1c46aa/plugin/bundleVisualizer.ts#L100, instead of calling the CLI. For reference, we can look at this https://github.com/btd/esbuild-visualizer/blob/b28bc694b6f5391038366cfa543cdffc28d9068c/bin/cli.ts#L58.

Having this change will mean that we could move the dependency to `dependencies` and moreover remove all the checks on the npm packager.

I will take this on during the following week(s), let me know if you want to do it 😉
